import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        heading: ['"Space Grotesk"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        surface: "hsl(var(--surface))",
        glow: "hsl(var(--glow))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        vivid: {
          "error": "#ba1a1a",
          "surface": "#f8f9ff",
          "primary-fixed": "#ffdbcc",
          "outline-variant": "#e2bfb0",
          "on-secondary-container": "#f9f7ff",
          "surface-container-lowest": "#ffffff",
          "surface-container-highest": "#e1e2e8",
          "on-primary": "#ffffff",
          "surface-dim": "#d8dadf",
          "error-container": "#ffdad6",
          "surface-variant": "#e1e2e8",
          "tertiary-container": "#939aa1",
          "primary-fixed-dim": "#ffb693",
          "surface-container-high": "#e6e8ed",
          "tertiary": "#585f66",
          "secondary-fixed-dim": "#b3c5ff",
          "background": "#f8f9ff",
          "secondary": "#0050cc",
          "on-error": "#ffffff",
          "on-error-container": "#93000a",
          "inverse-primary": "#ffb693",
          "on-tertiary-fixed": "#151c22",
          "on-tertiary": "#ffffff",
          "on-tertiary-fixed-variant": "#40484e",
          "on-primary-fixed-variant": "#7a3000",
          "inverse-surface": "#2e3135",
          "on-background": "#191c20",
          "surface-container": "#eceef3",
          "primary": "#a04100",
          "tertiary-fixed": "#dce3eb",
          "on-secondary-fixed": "#001849",
          "surface-container-low": "#f2f3f9",
          "on-tertiary-container": "#2b3238",
          "primary-container": "#ff6b00",
          "on-secondary-fixed-variant": "#003fa4",
          "on-surface": "#191c20",
          "surface-tint": "#a04100",
          "on-primary-fixed": "#351000",
          "secondary-container": "#0266ff",
          "secondary-fixed": "#dae1ff",
          "on-surface-variant": "#5a4136",
          "on-secondary": "#ffffff",
          "on-primary-container": "#572000",
          "outline": "#8e7164",
          "surface-bright": "#f8f9ff",
          "inverse-on-surface": "#eff0f6",
          "tertiary-fixed-dim": "#c0c7cf"
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "1" },
        },
        "marquee": {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-up": "fade-up 0.6s ease-out forwards",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
        "marquee": "marquee 15s linear infinite",
      },
      fontFamily: {
        "heading": ['"Space Grotesk"', 'sans-serif'],
        "body": ['"Inter"', 'sans-serif'],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-sm": ['"Merriweather"', "serif"],
        "label-bold": ["Inter", "sans-serif"],
        "display-lg-mobile": ['"Merriweather"', "serif"],
        "headline-md": ['"Merriweather"', "serif"],
        "display-lg": ['"Merriweather"', "serif"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-bold": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "display-lg-mobile": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "800" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "display-lg": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "800" }]
      },
      spacing: {
        "container-max": "1200px",
        "base": "8px",
        "section-padding-desktop": "120px",
        "gutter": "24px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        "stack-md": "24px",
        "section-padding-mobile": "64px"
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
